CREATE INDEX IF NOT EXISTS idx_cards_due ON cards (due);
CREATE INDEX IF NOT EXISTS idx_decks_user_id ON decks (user_id);
CREATE INDEX IF NOT EXISTS idx_cards_deck_id ON cards (deck_id);
CREATE INDEX IF NOT EXISTS idx_cards_deck_id_due ON cards (deck_id, due);
CREATE INDEX IF NOT EXISTS idx_review_logs_user_id ON review_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_review_logs_card_id ON review_logs (card_id);
CREATE INDEX IF NOT EXISTS idx_cards_deck_state_due ON cards (deck_id, state, due);
CREATE INDEX IF NOT EXISTS idx_review_logs_user_id_review ON review_logs (user_id, review);
CREATE INDEX IF NOT EXISTS idx_review_logs_card_id_review ON review_logs (card_id, review);
CREATE INDEX IF NOT EXISTS idx_decks_user_id_created_at ON decks (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
