#!/usr/bin/env sh

docker compose run --rm -T tools sh -c "npx -y @nodesify/graphify update ." || exit 1
git add .graphify/

npx lint-staged || exit 1

docker compose run --rm -T frontend sh -c "npm install --no-audit --no-fund --loglevel=error && npx eslint ." || exit 1